#!/bin/bash
# Skript tervitab jooksva kasutajat tema kasutajanimega, kus nimi algab suurtähega

# Võtame kasutajanime keskkonnamuutujast $USER
username=$USER

# Teeme esimese tähe suureks ja ülejäänud väikseks
username="$(tr '[:lower:]' '[:upper:]' <<< ${username:0:1})${username:1}"

echo -n "Tere, "
echo -n "$username"
echo "!"


