#!/bin/bash
# Skript kuvab kasutajale tervitust "Tere, Kasutajanimi !", kus kasutajanimi on esitähega suure tähega ja ülejäänud väikeste tähtedega

# Kasutajanimi väikestena
nimi_lower=$(echo "$USER" | tr '[:upper:]' '[:lower:]')

# Esimene täht suureks, ülejäänud väikesteks
nimi="$(echo ${nimi_lower:0:1} | tr '[:lower:]' '[:upper:]')${nimi_lower:1}"

# Väljasta tervitus
echo -n "Tere, "
echo -n "$nimi"
echo " !"

